default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRESQL_USERNAME")%>
  password: <%= ENV.fetch("POSTGRESQL_PASSWORD")%>
  host: <%= ENV.fetch("POSTGRESQL_HOST")%>
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_DATABASE_DEVELOPMENT")%>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_DATABASE_TEST")%>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRESQL_DATABASE_PRODUCTION") %>
